name: Pull Request Auto Label Review

on:
  pull_request_review:
    types:
      - submitted

permissions:
  pull-requests: write

jobs:
  remove:
    if: github.event.review.state == 'approved' || github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "Waiting for review"

  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "LGTM"

  ChangesRequested:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "DO NOT MERGE"
